# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import sessions_pb2 as sessions__pb2


class SessionsDispatcherStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddSession = channel.unary_unary(
                '/com.example.grpc.SessionsDispatcher/AddSession',
                request_serializer=sessions__pb2.Session.SerializeToString,
                response_deserializer=sessions__pb2.Reply.FromString,
                )
        self.DeleteSession = channel.unary_unary(
                '/com.example.grpc.SessionsDispatcher/DeleteSession',
                request_serializer=sessions__pb2.Session.SerializeToString,
                response_deserializer=sessions__pb2.Reply.FromString,
                )
        self.GetSessions = channel.unary_stream(
                '/com.example.grpc.SessionsDispatcher/GetSessions',
                request_serializer=sessions__pb2.Void.SerializeToString,
                response_deserializer=sessions__pb2.Session.FromString,
                )


class SessionsDispatcherServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SessionsDispatcherServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddSession': grpc.unary_unary_rpc_method_handler(
                    servicer.AddSession,
                    request_deserializer=sessions__pb2.Session.FromString,
                    response_serializer=sessions__pb2.Reply.SerializeToString,
            ),
            'DeleteSession': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSession,
                    request_deserializer=sessions__pb2.Session.FromString,
                    response_serializer=sessions__pb2.Reply.SerializeToString,
            ),
            'GetSessions': grpc.unary_stream_rpc_method_handler(
                    servicer.GetSessions,
                    request_deserializer=sessions__pb2.Void.FromString,
                    response_serializer=sessions__pb2.Session.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.example.grpc.SessionsDispatcher', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SessionsDispatcher(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.example.grpc.SessionsDispatcher/AddSession',
            sessions__pb2.Session.SerializeToString,
            sessions__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.example.grpc.SessionsDispatcher/DeleteSession',
            sessions__pb2.Session.SerializeToString,
            sessions__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/com.example.grpc.SessionsDispatcher/GetSessions',
            sessions__pb2.Void.SerializeToString,
            sessions__pb2.Session.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
