# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sessions.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sessions.proto',
  package='com.example.grpc',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0esessions.proto\x12\x10\x63om.example.grpc\"\x15\n\x07Session\x12\n\n\x02ip\x18\x01 \x01(\t\"\x17\n\x05Reply\x12\x0e\n\x06status\x18\x01 \x01(\x05\"\x06\n\x04Void2\xdf\x01\n\x12SessionsDispatcher\x12@\n\nAddSession\x12\x19.com.example.grpc.Session\x1a\x17.com.example.grpc.Reply\x12\x43\n\rDeleteSession\x12\x19.com.example.grpc.Session\x1a\x17.com.example.grpc.Reply\x12\x42\n\x0bGetSessions\x12\x16.com.example.grpc.Void\x1a\x19.com.example.grpc.Session0\x01\x62\x06proto3'
)




_SESSION = _descriptor.Descriptor(
  name='Session',
  full_name='com.example.grpc.Session',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='com.example.grpc.Session.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=57,
)


_REPLY = _descriptor.Descriptor(
  name='Reply',
  full_name='com.example.grpc.Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='com.example.grpc.Reply.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=82,
)


_VOID = _descriptor.Descriptor(
  name='Void',
  full_name='com.example.grpc.Void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=90,
)

DESCRIPTOR.message_types_by_name['Session'] = _SESSION
DESCRIPTOR.message_types_by_name['Reply'] = _REPLY
DESCRIPTOR.message_types_by_name['Void'] = _VOID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Session = _reflection.GeneratedProtocolMessageType('Session', (_message.Message,), {
  'DESCRIPTOR' : _SESSION,
  '__module__' : 'sessions_pb2'
  # @@protoc_insertion_point(class_scope:com.example.grpc.Session)
  })
_sym_db.RegisterMessage(Session)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), {
  'DESCRIPTOR' : _REPLY,
  '__module__' : 'sessions_pb2'
  # @@protoc_insertion_point(class_scope:com.example.grpc.Reply)
  })
_sym_db.RegisterMessage(Reply)

Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), {
  'DESCRIPTOR' : _VOID,
  '__module__' : 'sessions_pb2'
  # @@protoc_insertion_point(class_scope:com.example.grpc.Void)
  })
_sym_db.RegisterMessage(Void)



_SESSIONSDISPATCHER = _descriptor.ServiceDescriptor(
  name='SessionsDispatcher',
  full_name='com.example.grpc.SessionsDispatcher',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=93,
  serialized_end=316,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddSession',
    full_name='com.example.grpc.SessionsDispatcher.AddSession',
    index=0,
    containing_service=None,
    input_type=_SESSION,
    output_type=_REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteSession',
    full_name='com.example.grpc.SessionsDispatcher.DeleteSession',
    index=1,
    containing_service=None,
    input_type=_SESSION,
    output_type=_REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetSessions',
    full_name='com.example.grpc.SessionsDispatcher.GetSessions',
    index=2,
    containing_service=None,
    input_type=_VOID,
    output_type=_SESSION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SESSIONSDISPATCHER)

DESCRIPTOR.services_by_name['SessionsDispatcher'] = _SESSIONSDISPATCHER

# @@protoc_insertion_point(module_scope)
